spring:
  config:
    name: Pr3_DB
  datasource:
    url: jdbc:postgresql://localhost:5432/Ofice_mag
    username: postgres
    password: 2005
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql:
server:
  port: 8888
